Rscript run_SHAP_test.r 1 1 training RF
Rscript run_SHAP_test.r 1 1 training lasso
Rscript run_SHAP_test.r 1 1 testing RF
Rscript run_SHAP_test.r 1 1 testing lasso
Rscript run_SHAP_test.r 1 2 training RF
Rscript run_SHAP_test.r 1 2 training lasso
Rscript run_SHAP_test.r 1 2 testing RF
Rscript run_SHAP_test.r 1 2 testing lasso
Rscript run_SHAP_test.r 1 3 training RF
Rscript run_SHAP_test.r 1 3 training lasso
Rscript run_SHAP_test.r 1 3 testing RF
Rscript run_SHAP_test.r 1 3 testing lasso
Rscript run_SHAP_test.r 1 4 training RF
Rscript run_SHAP_test.r 1 4 training lasso
Rscript run_SHAP_test.r 1 4 testing RF
Rscript run_SHAP_test.r 1 4 testing lasso
Rscript run_SHAP_test.r 1 5 training RF
Rscript run_SHAP_test.r 1 5 training lasso
Rscript run_SHAP_test.r 1 5 testing RF
Rscript run_SHAP_test.r 1 5 testing lasso
Rscript run_SHAP_test.r 1 6 training RF
Rscript run_SHAP_test.r 1 6 training lasso
Rscript run_SHAP_test.r 1 6 testing RF
Rscript run_SHAP_test.r 1 6 testing lasso
Rscript run_SHAP_test.r 1 7 training RF
Rscript run_SHAP_test.r 1 7 training lasso
Rscript run_SHAP_test.r 1 7 testing RF
Rscript run_SHAP_test.r 1 7 testing lasso
Rscript run_SHAP_test.r 1 8 training RF
Rscript run_SHAP_test.r 1 8 training lasso
Rscript run_SHAP_test.r 1 8 testing RF
Rscript run_SHAP_test.r 1 8 testing lasso
Rscript run_SHAP_test.r 1 9 training RF
Rscript run_SHAP_test.r 1 9 training lasso
Rscript run_SHAP_test.r 1 9 testing RF
Rscript run_SHAP_test.r 1 9 testing lasso
Rscript run_SHAP_test.r 1 10 training RF
Rscript run_SHAP_test.r 1 10 training lasso
Rscript run_SHAP_test.r 1 10 testing RF
Rscript run_SHAP_test.r 1 10 testing lasso
Rscript run_SHAP_test.r 2 1 training RF
Rscript run_SHAP_test.r 2 1 training lasso
Rscript run_SHAP_test.r 2 1 testing RF
Rscript run_SHAP_test.r 2 1 testing lasso
Rscript run_SHAP_test.r 2 2 training RF
Rscript run_SHAP_test.r 2 2 training lasso
Rscript run_SHAP_test.r 2 2 testing RF
Rscript run_SHAP_test.r 2 2 testing lasso
Rscript run_SHAP_test.r 2 3 training RF
Rscript run_SHAP_test.r 2 3 training lasso
Rscript run_SHAP_test.r 2 3 testing RF
Rscript run_SHAP_test.r 2 3 testing lasso
Rscript run_SHAP_test.r 2 4 training RF
Rscript run_SHAP_test.r 2 4 training lasso
Rscript run_SHAP_test.r 2 4 testing RF
Rscript run_SHAP_test.r 2 4 testing lasso
Rscript run_SHAP_test.r 2 5 training RF
Rscript run_SHAP_test.r 2 5 training lasso
Rscript run_SHAP_test.r 2 5 testing RF
Rscript run_SHAP_test.r 2 5 testing lasso
Rscript run_SHAP_test.r 2 6 training RF
Rscript run_SHAP_test.r 2 6 training lasso
Rscript run_SHAP_test.r 2 6 testing RF
Rscript run_SHAP_test.r 2 6 testing lasso
Rscript run_SHAP_test.r 2 7 training RF
Rscript run_SHAP_test.r 2 7 training lasso
Rscript run_SHAP_test.r 2 7 testing RF
Rscript run_SHAP_test.r 2 7 testing lasso
Rscript run_SHAP_test.r 2 8 training RF
Rscript run_SHAP_test.r 2 8 training lasso
Rscript run_SHAP_test.r 2 8 testing RF
Rscript run_SHAP_test.r 2 8 testing lasso
Rscript run_SHAP_test.r 2 9 training RF
Rscript run_SHAP_test.r 2 9 training lasso
Rscript run_SHAP_test.r 2 9 testing RF
Rscript run_SHAP_test.r 2 9 testing lasso
Rscript run_SHAP_test.r 2 10 training RF
Rscript run_SHAP_test.r 2 10 training lasso
Rscript run_SHAP_test.r 2 10 testing RF
Rscript run_SHAP_test.r 2 10 testing lasso
Rscript run_SHAP_test.r 3 1 training RF
Rscript run_SHAP_test.r 3 1 training lasso
Rscript run_SHAP_test.r 3 1 testing RF
Rscript run_SHAP_test.r 3 1 testing lasso
Rscript run_SHAP_test.r 3 2 training RF
Rscript run_SHAP_test.r 3 2 training lasso
Rscript run_SHAP_test.r 3 2 testing RF
Rscript run_SHAP_test.r 3 2 testing lasso
Rscript run_SHAP_test.r 3 3 training RF
Rscript run_SHAP_test.r 3 3 training lasso
Rscript run_SHAP_test.r 3 3 testing RF
Rscript run_SHAP_test.r 3 3 testing lasso
Rscript run_SHAP_test.r 3 4 training RF
Rscript run_SHAP_test.r 3 4 training lasso
Rscript run_SHAP_test.r 3 4 testing RF
Rscript run_SHAP_test.r 3 4 testing lasso
Rscript run_SHAP_test.r 3 5 training RF
Rscript run_SHAP_test.r 3 5 training lasso
Rscript run_SHAP_test.r 3 5 testing RF
Rscript run_SHAP_test.r 3 5 testing lasso
Rscript run_SHAP_test.r 3 6 training RF
Rscript run_SHAP_test.r 3 6 training lasso
Rscript run_SHAP_test.r 3 6 testing RF
Rscript run_SHAP_test.r 3 6 testing lasso
Rscript run_SHAP_test.r 3 7 training RF
Rscript run_SHAP_test.r 3 7 training lasso
Rscript run_SHAP_test.r 3 7 testing RF
Rscript run_SHAP_test.r 3 7 testing lasso
Rscript run_SHAP_test.r 3 8 training RF
Rscript run_SHAP_test.r 3 8 training lasso
Rscript run_SHAP_test.r 3 8 testing RF
Rscript run_SHAP_test.r 3 8 testing lasso
Rscript run_SHAP_test.r 3 9 training RF
Rscript run_SHAP_test.r 3 9 training lasso
Rscript run_SHAP_test.r 3 9 testing RF
Rscript run_SHAP_test.r 3 9 testing lasso
Rscript run_SHAP_test.r 3 10 training RF
Rscript run_SHAP_test.r 3 10 training lasso
Rscript run_SHAP_test.r 3 10 testing RF
Rscript run_SHAP_test.r 3 10 testing lasso
Rscript run_SHAP_test.r 4 1 training RF
Rscript run_SHAP_test.r 4 1 training lasso
Rscript run_SHAP_test.r 4 1 testing RF
Rscript run_SHAP_test.r 4 1 testing lasso
Rscript run_SHAP_test.r 4 2 training RF
Rscript run_SHAP_test.r 4 2 training lasso
Rscript run_SHAP_test.r 4 2 testing RF
Rscript run_SHAP_test.r 4 2 testing lasso
Rscript run_SHAP_test.r 4 3 training RF
Rscript run_SHAP_test.r 4 3 training lasso
Rscript run_SHAP_test.r 4 3 testing RF
Rscript run_SHAP_test.r 4 3 testing lasso
Rscript run_SHAP_test.r 4 4 training RF
Rscript run_SHAP_test.r 4 4 training lasso
Rscript run_SHAP_test.r 4 4 testing RF
Rscript run_SHAP_test.r 4 4 testing lasso
Rscript run_SHAP_test.r 4 5 training RF
Rscript run_SHAP_test.r 4 5 training lasso
Rscript run_SHAP_test.r 4 5 testing RF
Rscript run_SHAP_test.r 4 5 testing lasso
Rscript run_SHAP_test.r 4 6 training RF
Rscript run_SHAP_test.r 4 6 training lasso
Rscript run_SHAP_test.r 4 6 testing RF
Rscript run_SHAP_test.r 4 6 testing lasso
Rscript run_SHAP_test.r 4 7 training RF
Rscript run_SHAP_test.r 4 7 training lasso
Rscript run_SHAP_test.r 4 7 testing RF
Rscript run_SHAP_test.r 4 7 testing lasso
Rscript run_SHAP_test.r 4 8 training RF
Rscript run_SHAP_test.r 4 8 training lasso
Rscript run_SHAP_test.r 4 8 testing RF
Rscript run_SHAP_test.r 4 8 testing lasso
Rscript run_SHAP_test.r 4 9 training RF
Rscript run_SHAP_test.r 4 9 training lasso
Rscript run_SHAP_test.r 4 9 testing RF
Rscript run_SHAP_test.r 4 9 testing lasso
Rscript run_SHAP_test.r 4 10 training RF
Rscript run_SHAP_test.r 4 10 training lasso
Rscript run_SHAP_test.r 4 10 testing RF
Rscript run_SHAP_test.r 4 10 testing lasso
Rscript run_SHAP_test.r 5 1 training RF
Rscript run_SHAP_test.r 5 1 training lasso
Rscript run_SHAP_test.r 5 1 testing RF
Rscript run_SHAP_test.r 5 1 testing lasso
Rscript run_SHAP_test.r 5 2 training RF
Rscript run_SHAP_test.r 5 2 training lasso
Rscript run_SHAP_test.r 5 2 testing RF
Rscript run_SHAP_test.r 5 2 testing lasso
Rscript run_SHAP_test.r 5 3 training RF
Rscript run_SHAP_test.r 5 3 training lasso
Rscript run_SHAP_test.r 5 3 testing RF
Rscript run_SHAP_test.r 5 3 testing lasso
Rscript run_SHAP_test.r 5 4 training RF
Rscript run_SHAP_test.r 5 4 training lasso
Rscript run_SHAP_test.r 5 4 testing RF
Rscript run_SHAP_test.r 5 4 testing lasso
Rscript run_SHAP_test.r 5 5 training RF
Rscript run_SHAP_test.r 5 5 training lasso
Rscript run_SHAP_test.r 5 5 testing RF
Rscript run_SHAP_test.r 5 5 testing lasso
Rscript run_SHAP_test.r 5 6 training RF
Rscript run_SHAP_test.r 5 6 training lasso
Rscript run_SHAP_test.r 5 6 testing RF
Rscript run_SHAP_test.r 5 6 testing lasso
Rscript run_SHAP_test.r 5 7 training RF
Rscript run_SHAP_test.r 5 7 training lasso
Rscript run_SHAP_test.r 5 7 testing RF
Rscript run_SHAP_test.r 5 7 testing lasso
Rscript run_SHAP_test.r 5 8 training RF
Rscript run_SHAP_test.r 5 8 training lasso
Rscript run_SHAP_test.r 5 8 testing RF
Rscript run_SHAP_test.r 5 8 testing lasso
Rscript run_SHAP_test.r 5 9 training RF
Rscript run_SHAP_test.r 5 9 training lasso
Rscript run_SHAP_test.r 5 9 testing RF
Rscript run_SHAP_test.r 5 9 testing lasso
Rscript run_SHAP_test.r 5 10 training RF
Rscript run_SHAP_test.r 5 10 training lasso
Rscript run_SHAP_test.r 5 10 testing RF
Rscript run_SHAP_test.r 5 10 testing lasso
