Rscript run_SHAP_test.r 1 1 training
Rscript run_SHAP_test.r 1 2 training
Rscript run_SHAP_test.r 1 3 training
Rscript run_SHAP_test.r 1 4 training
Rscript run_SHAP_test.r 1 5 training
Rscript run_SHAP_test.r 1 6 training
Rscript run_SHAP_test.r 1 7 training
Rscript run_SHAP_test.r 1 8 training
Rscript run_SHAP_test.r 1 9 training
Rscript run_SHAP_test.r 1 10 training
Rscript run_SHAP_test.r 2 1 training
Rscript run_SHAP_test.r 2 2 training
Rscript run_SHAP_test.r 2 3 training
Rscript run_SHAP_test.r 2 4 training
Rscript run_SHAP_test.r 2 5 training
Rscript run_SHAP_test.r 2 6 training
Rscript run_SHAP_test.r 2 7 training
Rscript run_SHAP_test.r 2 8 training
Rscript run_SHAP_test.r 2 9 training
Rscript run_SHAP_test.r 2 10 training
Rscript run_SHAP_test.r 3 1 training
Rscript run_SHAP_test.r 3 2 training
Rscript run_SHAP_test.r 3 3 training
Rscript run_SHAP_test.r 3 4 training
Rscript run_SHAP_test.r 3 5 training
Rscript run_SHAP_test.r 3 6 training
Rscript run_SHAP_test.r 3 7 training
Rscript run_SHAP_test.r 3 8 training
Rscript run_SHAP_test.r 3 9 training
Rscript run_SHAP_test.r 3 10 training
Rscript run_SHAP_test.r 4 1 training
Rscript run_SHAP_test.r 4 2 training
Rscript run_SHAP_test.r 4 3 training
Rscript run_SHAP_test.r 4 4 training
Rscript run_SHAP_test.r 4 5 training
Rscript run_SHAP_test.r 4 6 training
Rscript run_SHAP_test.r 4 7 training
Rscript run_SHAP_test.r 4 8 training
Rscript run_SHAP_test.r 4 9 training
Rscript run_SHAP_test.r 4 10 training
Rscript run_SHAP_test.r 5 1 training
Rscript run_SHAP_test.r 5 2 training
Rscript run_SHAP_test.r 5 3 training
Rscript run_SHAP_test.r 5 4 training
Rscript run_SHAP_test.r 5 5 training
Rscript run_SHAP_test.r 5 6 training
Rscript run_SHAP_test.r 5 7 training
Rscript run_SHAP_test.r 5 8 training
Rscript run_SHAP_test.r 5 9 training
Rscript run_SHAP_test.r 5 10 training
